#  __      __        _         _____          _ _             
#  \ \    / /       (_)       / ____|        | (_)            
#   \ \  / /__ _ __  ___  __ | |     ___   __| |_ _ __   __ _ 
#    \ \/ / _ \ '_ \| \ \/ / | |    / _ \ / _` | | '_ \ / _` |
#     \  /  __/ | | | |>  <  | |___| (_) | (_| | | | | | (_| |
#      \/ \___|_| |_|_/_/\_\  \_____\___/ \__,_|_|_| |_|\__, |
#                                                        __/ |
#                   By [VenixCoding - Devo]             |___/ 


# default speed: 1.0
# Recommended speed: 1.7, 1.9, 2.0
FastRod:
  speed: 1.0
  sound: true